database:
    host: localhost
    port: 5432
    protocol: postgres
    user: postgres
    password: postgres
    dbname: indweathdb

oweather_apikey: e4d25c020947523c7c18b8e4af1ce00e
service:
    port: 8080
    readTimeout: 